### ISSUE TITLE
[Question] BigQuery delay/deferment to get user enrollment event

### ISSUE THREAD

**Issue by jbaker10** [google/loaner#55]
Hi all, this is more a question than an issue. We are trying to audit loan check-outs and returns with a ~5 min granularity (as in, we want to know who checked out what device within the last 5 minutes). We thought we could get this info from BigQuery, but it seems the data doesn't appear there for several minutes (we've seen up to a 20 min delay). I found the data in the `BigQueryRow` datastore, however, I am unable to do any sort of complex queries on these rows (to sort by timestamp for example). We have tried adding the following to the index.yaml and re-deploying to see if the added fields will get indexed, but unfortunately had no extra luck.

```
- kind: BigQueryRow
  properties:
  - name: streamed
  - name: timestamp
  - name: actor
  - name: method
  - name: model_type
```

Is there a way to get this data into BigQuery faster, or perhaps a better way to know about these events happening? Ideally this could be something like a webhook, but I didn't see that functionality available. I also saw references to `custom_actions`, but was confused on how to get started with those.

Thanks for any insight and assistance you can offer!
